### ISSUE TITLE
Add jumper that either connects EXMEM to ground or leaves it disconnected

### ISSUE THREAD

**Issue by niklasekstrom** [niklasekstrom/a314#10]
The mod that makes A500 rev 6A get 1 MB chip mem (instead of 0.5 MB chip and 0.5 MB slow) which is described here, https://s6.postimg.cc/53hat1xkh/A500_6a_1_MBCHIP.png, requires soldering two jumpers on the motherboard. By adding a jumper on A314 it would be possible to avoid soldering JP7; however JP2 still needs soldering.

**Comment by Eriond** [comment]
Modifications are done. New PCBs are ordered, and once we get to verify them in the coming weeks, the repo will be updated with new files.

**Comment by niklasekstrom** [comment]
Fixed by the PCB 1.1 update.
