### ISSUE TITLE
Add jumper that disconnects RAS0

### ISSUE THREAD

**Issue by niklasekstrom** [niklasekstrom/a314#11]
It is possible to cut traces on JP3 on the A500 motherboard, and thereby disable the on-motherboard DRAM. In that case, A314 should respond to DRAM-requests for RAS0 as well as RAS1. But if the firmware is modified so that A314 responds to RAS0-requests then there will be collisions when running on an A500 whose JP3 traces are not cut. Therefore a jumper on A314 would be useful to disconnect RAS0 when the JP3 traces are not cut.

This jumper would also be useful for A500+, so that a single FPGA programming file can be used regardless if the A314 is going to be used in an A500 or an A500+.

**Comment by Eriond** [comment]
Modifications are done. New PCBs are ordered, and once we get to verify them in the coming weeks, the repo will be updated with new files.

**Comment by niklasekstrom** [comment]
Fixed by the PCB 1.1 update.
