### ISSUE TITLE
Create a preconfigured boot floppy

### ISSUE THREAD

**Issue by niklasekstrom** [niklasekstrom/a314#13]
It would help if there was a preconfigured floppy that could be download with all software on it needed to boot up an A314 board.

**Comment by arnljot** [comment]
This could be built upon the AROS m68k boot floppy. This way all license issues are avoided, and one still has a floppy in adf (I presume) that one can write, boot and install from on the amiga.

**Comment by niklasekstrom** [comment]
The files for this disk are now available in the release, so I'm closing the issue for now.
