### ISSUE TITLE
Does that board also allow CHIP RAM extensions?

### ISSUE THREAD

**Issue by hlide** [niklasekstrom/a314#17]
It is not very clear if that board also offers true chip RAM extension to allow A500 rev6A to get 1 MB or A500+ to get 2 MB. Moreover, there are some moddings which allow to get 2 MB on an A500 ev6A involving the change of an Agnus chip.

There is also the case of [the Boobip board](http://www.boobip.com/hardware/A500_2MB) which allow a clever way to maximize the chip RAM size and getting the rest as slow RAM. I wonder if it would be possible to make A314 compatible with the Boobip in such a way you only need a Gary adapter board, connecting cables and jumper wires (for full 2MB mod) while A314 may acte as the memory board.

**Comment by niklasekstrom** [comment]
Hi!

> It is not very clear if that board also offers true chip RAM extension to allow A500 rev6A to get 1 MB or A500+ to get 2 MB.

A314 has 1MB SRAM on the board, and behaves as a normal A501(+) memory expansion. This means that on an A500 rev 6A with the 1MB chip mem mod (as described here https://s6.postimg.cc/53hat1xkh/A500_6a_1_MBCHIP.png) the A314 provides another 512kB chip mem, for a total of 1MB chip. In an A500+ A314 provides an extra 1MB chip mem, for a total of 2MB chip mem. We actually tried the A314 in an A500+ for the first time yesterday night and it works well; currently there's a separate branch for A500+, https://github.com/niklasekstrom/a314/tree/one_mb, but it will be merged into master shortly.

> There is also the case of the Boobip board which allow a clever way to maximize the chip RAM size and getting the rest as slow RAM.

There is currently no support for using the other 512kB memory in an A500 rev 6A with a Gary adapter, as is done with the Boobip board, but maybe that is something that someone can add in the future?

Another option is to disable the internal 512kB chip mem in an A500 rev 6A, as described here https://github.com/niklasekstrom/a314/issues/11, and let A314 provide all 1MB chip; the benefit is that the whole 1MB is then accessible to the raspberry pi.
