### ISSUE TITLE
Create an audio device in Linux (running on the RPi) that outputs sound via Paula

### ISSUE THREAD

**Issue by niklasekstrom** [niklasekstrom/a314#20]
I'm not sure how hard this would be, but if possible it could be nice to make a sound device for Linux, running on the RPi, that writes the sound samples to A314 memory and then sets it up on the Amiga side so that the sound is played by Paula. I'm guessing this would allocate two of the four Amiga audio channels.

**Comment by aiobofh** [comment]
This would be really cool. Kind of a channel-mixer outputting 14-bit sound!? :)

**Comment by niklasekstrom** [comment]
It seems like it may be possible to use the ALSA file (or shm) plugin (https://www.alsa-project.org/alsa-doc/alsa-lib/pcm_plugins.html) to obtain samples in a format suitable to write to Amiga chip memory.

This is what I've got so far for .asoundrc:

pcm.tofile {
    type file
    format raw
    file /tmp/out.raw
    slave.pcm null
}

pcm.amiga {
    type plug
    slave {
        pcm tofile
        format S8
        channels 2
        rate 16000
    }
    hint {
        description "Changes format to match Amiga"
    }
}
