### ISSUE TITLE
Idea: Make Chucky add this to the ReAmiga1200 and ReAmiga3000 motherboards in the future

### ISSUE THREAD

**Issue by aiobofh** [niklasekstrom/a314#21]
By being able to access chip-RAM the same ways on these new-school remakes of Amiga motherboards there should be a solid user-base that would be able to benefit from A314 :D 

I guess the guys behind Amy and remakes of varius A4000 PCB's could do it too.

Just a crazy idea.

**Comment by aiobofh** [comment]
:) he's looking in to it

**Comment by niklasekstrom** [comment]
This idea isn't exactly an issue related to A314, but to those motherboards you mention. That being said, I think it would be completely awesome if someone integrated A314 into an Amiga motherboard! I'm all for it.
