### ISSUE TITLE
Docker suggestion

### ISSUE THREAD

**Issue by terriblefire** [niklasekstrom/a314#24]
Hi, great project

You could reuse my dockerfile and docker code to give people build environments for the drivers... 

Take a look 

https://github.com/terriblefire/cdtv.device

**Comment by terriblefire** [comment]
I just did this for you quickly.. here's a pull request.. doesnt touch any existing files 

https://github.com/niklasekstrom/a314/pull/25

**Comment by niklasekstrom** [comment]
Hey Stephen, that's a great suggestion. I will try it out this evening. Thanks!

**Comment by niklasekstrom** [comment]
That's excellent, thanks again.

I was planning to reorganize the directory structure a bit at some point, related to issue #15. If you have any thoughts or ideas about ways to do that I would be happy to hear them :)
