### ISSUE TITLE
Program FPGA firmware from RPi

### ISSUE THREAD

**Issue by niklasekstrom** [niklasekstrom/a314#29]
It chould be possible to connect additional pins from the RPi pin header to the FPGA JTAG pins, and then use the RPi for programming the FPGA firmware.

The program described on this page has been used successfully to program the firmware: https://weekly-geekly.github.io/articles/343524/index.html

**Comment by niklasekstrom** [comment]
The program mentioned above have been modified by its author (as suggested by Marcin) to make it configurable which RPi pins are used for the JTAG connection. https://translate.google.com/translate?hl=&sl=ru&tl=en&u=https%3A%2F%2Fmarsohod.org%2F397-pi4-m2rpi

**Comment by peon374** [comment]
The program talked about looks like it is intended to be a JTAG debugging server.  If you just wanted to use the connection to be able to upgrade the firmware on the MAX10, I think openOCD should be able to do this.  If the build process used to make the POF goes one step further and makes a SVF file as part of your release, it could be pulled in and flashed without any Quartus toolchain.

**Comment by Eriond** [comment]
That sounds really interesting! We would appreciate it if you could consider trying it out?

**Comment by Eriond** [comment]
Issue resolved with updated PCB layout, v1.2
