### ISSUE TITLE
Make a314d check spidev.bufsiz setting.

### ISSUE THREAD

**Issue by arnljot** [niklasekstrom/a314#37]
We've got experience that this setting is very important and that users are missing out on setting it correctly.

a314d should check this on startup, and refuse to run if not set correctly. Maybe just start in a minimal mode without services so that a314.device won't hang on the amiga side? Investigation needed.

if not spidev.bufsiz=65536 then log.error "spidev.bufsiz not set to correct value, check spelling?"

**Comment by niklasekstrom** [comment]
I noticed that the value that is currently in use can be read from /sys/module/spidev/parameters/bufsiz, so it should be easy to do this check when a314d is started.
