### ISSUE TITLE
The generated BOM is not in a format that works with suppliers

### ISSUE THREAD

**Issue by peon374** [niklasekstrom/a314#38]
Can we get an export of the BOM that works with octopart and/or digikey?

**Comment by Eriond** [comment]
The BOM was never intended to be in a supplier-compatible format. It consists of 34 different components.
I believe that typing them in manually shouldn't stop anyone from building their own card. And, as a courtesy, I took the time to add DigiKey part numbers to make it even simpler. That's as much effort as I'm willing to spend on this matter.

**Comment by peon374** [comment]
All you need to do is add a data format like CSV.  It is probably one of the default export options.

**Comment by niklasekstrom** [comment]
@peon374 If you like to create such a CSV file then feel free to contribute the file back to the repo with a pull request. I don't think it makes sense that you insist that someone else should do that for you.

**Comment by peon374** [comment]
Awesome, will do shortly.
