### ISSUE TITLE
V1.2 BOM is wrong

### ISSUE THREAD

**Issue by peon374** [niklasekstrom/a314#40]
This is why you should machine generate the BOM.  Your resistor pack in the BOM has the wrong quantity (3 instead of 4)

**Comment by Eriond** [comment]
This has now been corrected. thank you for pointing it out.
The BOM is machine generated using the BOM.ulp from Eagle CAD. But there are components that aren't present in the schematic such as wires, LED connectors and jumpers, so manual modifications had to be made. I guess that during this process, a human error snuck by.
