### ISSUE TITLE
a314eth.device should avoid calling AllocSignal() on the schedule of the client, which happens to be the TCP/IP stack

### ISSUE THREAD

**Issue by obarthel** [niklasekstrom/a314#41]
I know, a314eth.device is still new :-)

Some rules for device drivers are peculiar, and the device init/exit code still needs work.

But for network device drivers for which the TCP/IP stack (or Envoy) is the only client, there are additional perils. If you call AllocSignal() in the device open/close function, it may actually fail. You don't know how many free signals are still available for the taking.

At the minimum, please check if AllocSignal() returns failure.

If the point is just to have a signal for communicating with the unit Process, you can avoid calling AllocSignal() altogether by using SIGB_SIGNAL (and its corresponding flag SIGF_SIGNAL) instead. There are some precoditions for doing so, though.

Happy to help you out if you want me to :-)

**Comment by niklasekstrom** [comment]
Thanks Olaf for pointing out this issue!

Please let me know if you see any other issues I should handle.
