### ISSUE TITLE
Create Linux installer for A314 for pre-existing setups

### ISSUE THREAD

**Issue by jeztucker** [niklasekstrom/a314#46]
Enable users with pre-existing SD cards to auto-magically install and configure the A314 software.
Increases:
- ease of use
Removes:
- blockers to adoption

Should be additionally shipped on pre-built image to aid re-installation.
Not doing: Version updates (new ticket).

**Comment by niklasekstrom** [comment]
An installer script (Software/install-pi.sh) has been added.
