### ISSUE TITLE
Raspberry Pi Compatibility

### ISSUE THREAD

**Issue by prgp** [niklasekstrom/a314#63]
I checked the wiki and was not able to locate a Raspberry Pi compatibility list.

As I understand it the Raspberry Pi is drawing power via the A500's trapdoor - what are the draw limits that this imposes on the Rapsberry Pi ? (a Zero has a maximum draw of about 300 mA and a Model 2B has a maximum draw of about 820 mA, but a model 4B has a maximum draw of about 1250 mA)

Would it be possible to add to the wiki which Raspberry Pi models have been used successfully.

**Comment by alestanga** [comment]
I'm using a RPi 2B in my Amiga 500 and it works flawlessly, well, if you don't mind the absence of WiFi.
ethernet works just fine though.

**Comment by Eriond** [comment]
compatibility list added. Issue may be closed.
