### ISSUE TITLE
Change to Compute Module instead of RPI GPIO Header

### ISSUE THREAD

**Issue by ryanm101** [niklasekstrom/a314#67]
I was thinking that if the compute module was used it might provide for neater installation and it might also allow full size rpi to fit in the A600.

Key issue I see is that there is now CM3 and CM4 which use a different connector and it might mean seperate board layouts for each due to them being very different. 
https://www.raspberrypi.org/documentation/hardware/computemodule/datasheet.md

This would also mean that if required things like ethernet connector could be offloaded to the A314 pcb

**Comment by niklasekstrom** [comment]
The issue of using CM3 (or not) for the A314-600 version has been discussed a few times, see for example the discussion in issue #18. I think it comes down to the price of adding back the components that are missing on the CM3 (compared to the full Pi 3B+), and the work to redesign the board. If you are interested in taking on this work then definitively let us know, as it would be nice to have the power of the Pi 3 in the smaller form factor.
