### ISSUE TITLE
remote-mouse no context menu with right-click on icons with activated magic-menu

### ISSUE THREAD

**Issue by hgw77** [niklasekstrom/a314#71]
I would like to report a problem with the remote-mouse and magic-menu. I tested it with scalos and diropus5 and found out that unfortunately the context menu for icons does not work. If I click on an icon and right-click I don't get the context menu of Scalos or DirOpus with the remote-mouse. Instead I get the global menu. When I disable magic-menu it is working.

**Comment by niklasekstrom** [comment]
I think this problematic interaction between RemoteMouse and MagicMenu is a bit too specific to spend time on.

If more people have this problem then we can reopen the issue.
