### ISSUE TITLE
A314cp problems using a Pi4 or CM4 under emu68 (PiStorm/PiStorm32 Lite)

### ISSUE THREAD

**Issue by katzazakis** [niklasekstrom/a314#82]
Using a Pi4 or CM4 (both versions) with a PiStorm or PiStorm32 under emu68 unfortunately makes the A314 clockport version unusable. All inputs, e.g. in the shell, are processed at a snail's pace and sometimes require multiple calls. It was tested on A500 with Lazarustorm and Clockport Adapter on the 68k socket and CM4 Lite/CM4 EMMC, second test with PiStorm32 Lite and Raspberry Pi4.
No problem using a Raspberry 3A+ on either configuration.

**Comment by niklasekstrom** [comment]
I was told that this issue has been fixed by an update to Emu68.
