### ISSUE TITLE
Missing Documentation for the disk Software

### ISSUE THREAD

**Issue by bugman1808** [niklasekstrom/a314#95]
Will be where a description how to eject and change adf disks while the Service is running?
Can it be triggered from the Amiga Side?

**Comment by niklasekstrom** [comment]
Hi @bugman1808, thank you for pointing out that this documentation was missing.

I have written a document that is available here: https://github.com/niklasekstrom/a314/blob/main/Software/disk/README.md

Feel free to point out if something is unclear or missing.
